version: '3'

services:
  cloudbind-api:
    build:
      context: ./..
      dockerfile: docker/Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev